server:
  port: 8082
  error:
    include-exception: on
    include-message: always
    include-stacktrace: never
    include-binding-errors: always

spring:
  application:
    name: hostel
  datasource:
    # you can change these credentials to your own
    username: postgres
    password: test@1234
    url: jdbc:postgresql://localhost:5432/attendance
  jpa:
    show-sql: true
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true